version: "3"

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=gumerovvlad
      - DB_NAME=terrafarm
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: E:\REACT-projects\terrafarm
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gumerovvlad
      POSTGRES_DB: terrafarm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
